In [2]:
seqA = "CCGGTTTTT"
seqB = "AGTTTAA"
seqC = "AGGTTT"
sequences = [seqA, seqB, seqC]
print(sequences)

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']


In [6]:
import numpy as np
coordinates = np.array([[1, 3, 4, 7, 9], [0, 2, 2, 5, 5], [0, 2, 3, 6, 6]])
print(coordinates)

[[1 3 4 7 9]
 [0 2 2 5 5]
 [0 2 3 6 6]]


In [7]:
from Bio.Align import Alignment
alignment = Alignment(sequences, coordinates)
alignment 

<Alignment object (3 rows x 8 columns) at 0x107578a90>

In [8]:
alignment.sequences

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']

In [11]:
alignment.coordinates

array([[1, 3, 4, 7, 9],
       [0, 2, 2, 5, 5],
       [0, 2, 3, 6, 6]])

In [12]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [13]:
lines = ["CGGTTTTT", "AG-TTT--", "AGGTTT--"]
for line in lines:
    print(line)

CGGTTTTT
AG-TTT--
AGGTTT--


In [14]:
lines = [line.encode() for line in lines]  # convert to bytes
lines

[b'CGGTTTTT', b'AG-TTT--', b'AGGTTT--']

In [15]:
sequences, coordinates = Alignment.parse_printed_alignment(lines)
sequences

[b'CGGTTTTT', b'AGTTT', b'AGGTTT']

In [16]:
sequences = [sequence.decode() for sequence in sequences]
sequences

['CGGTTTTT', 'AGTTT', 'AGGTTT']

In [17]:
print(coordinates)

[[0 2 3 6 8]
 [0 2 2 5 5]
 [0 2 3 6 6]]


In [18]:
from Bio.Seq import Seq
sequences[0] = "C" + sequences[0]
sequences[1] = sequences[1] + "AA"
sequences

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']

In [19]:
coordinates[0, :] += 1
print(coordinates)

[[1 3 4 7 9]
 [0 2 2 5 5]
 [0 2 3 6 6]]


In [20]:
alignment = Alignment(sequences, coordinates)
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [21]:
ungapped_alignment = Alignment(["ACGTACGT", "AAGTACGT", "ACGTACCT"])
ungapped_alignment  

<Alignment object (3 rows x 8 columns) at 0x10bc39e80>

In [22]:
print(ungapped_alignment.coordinates)

[[0 8]
 [0 8]
 [0 8]]


In [23]:
print(ungapped_alignment)

                  0 ACGTACGT 8
                  0 AAGTACGT 8
                  0 ACGTACCT 8



In [24]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [25]:
alignment.length

8

In [26]:
alignment[0]

'CGGTTTTT'

In [27]:
alignment[1]

'AG-TTT--'

In [28]:
alignment[2]

'AGGTTT--'

In [29]:
alignment[0, :]

'CGGTTTTT'

In [30]:
alignment[1, :]

'AG-TTT--'

In [31]:
alignment[0, 1:-1]

'GGTTTT'

In [32]:
alignment[1, 1:-1]

'G-TTT-'

In [33]:
alignment[0, (1, 2, 4)]

'GGT'

In [34]:
alignment[1, range(0, 5, 2)]

'A-T'

In [35]:
alignment[0, 2]

'G'

In [36]:
alignment[2, 6]

'-'

In [37]:
alignment[:, 0]

'CAA'

In [38]:
alignment[:, 1]

'GGG'

In [39]:
alignment[:, 2]

'G-G'

In [40]:
alignment[1:]

<Alignment object (2 rows x 6 columns) at 0x10bc39760>

In [41]:
print(alignment[1:])

target            0 AG-TTT 5
                  0 ||-||| 6
query             0 AGGTTT 6



In [42]:
alignment[:, :4] 

<Alignment object (3 rows x 4 columns) at 0x10bc39880>

In [43]:
print(alignment[:, :4])

                  1 CGGT 5
                  0 AG-T 3
                  0 AGGT 4



In [44]:
alignment[:, -6:] 

<Alignment object (3 rows x 6 columns) at 0x10bc39610>

In [45]:
print(alignment[:, -6:])

                  3 GTTTTT 9
                  2 -TTT-- 5
                  2 GTTT-- 6



In [46]:
print(alignment[:, (1, 3, 0)])

                  0 GTC 3
                  0 GTA 3
                  0 GTA 3



In [47]:
len(alignment)

3

In [48]:
alignment.length

8

In [49]:
alignment.shape

(3, 8)

In [50]:
pairwise_alignment = alignment[:2, :]
print(pairwise_alignment)

target            1 CGGTTTTT 9
                  0 .|-|||-- 8
query             0 AG-TTT-- 5



In [51]:
print(pairwise_alignment.aligned)

[[[1 3]
  [4 7]]

 [[0 2]
  [2 5]]]


In [53]:
pairwise_alignment1 = Alignment(["AAACAAA", "AAAGAAA"],
                                np.array([[0, 3, 4, 4, 7], [0, 3, 3, 4, 7]]))  # fmt: skip

pairwise_alignment2 = Alignment(["AAACAAA", "AAAGAAA"],
                                np.array([[0, 3, 3, 4, 7], [0, 3, 4, 4, 7]]))  # fmt: skip

print(pairwise_alignment1)

target            0 AAAC-AAA 7
                  0 |||--||| 8
query             0 AAA-GAAA 7



In [54]:
print(pairwise_alignment2)

target            0 AAA-CAAA 7
                  0 |||--||| 8
query             0 AAAG-AAA 7



In [55]:
pairwise_alignment1.aligned

array([[[0, 3],
        [4, 7]],

       [[0, 3],
        [4, 7]]])

In [56]:
pairwise_alignment2.aligned

array([[[0, 3],
        [4, 7]],

       [[0, 3],
        [4, 7]]])

In [57]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [58]:
alignment.indices

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 0,  1, -1,  2,  3,  4, -1, -1],
       [ 0,  1,  2,  3,  4,  5, -1, -1]])

In [59]:
alignment.sequences

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']

In [60]:
alignment.inverse_indices  

[array([-1,  0,  1,  2,  3,  4,  5,  6,  7]),
 array([ 0,  1,  3,  4,  5, -1, -1]),
 array([0, 1, 2, 3, 4, 5])]

In [61]:
print(pairwise_alignment)

target            1 CGGTTTTT 9
                  0 .|-|||-- 8
query             0 AG-TTT-- 5



In [62]:
pairwise_alignment.counts()

AlignmentCounts(gaps=3, identities=4, mismatches=1)

In [63]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [64]:
alignment.counts()

AlignmentCounts(gaps=8, identities=14, mismatches=2)

In [65]:
alignment.frequencies

{'C': array([1., 0., 0., 0., 0., 0., 0., 0.]),
 'G': array([0., 3., 2., 0., 0., 0., 0., 0.]),
 'T': array([0., 0., 0., 3., 3., 3., 1., 1.]),
 'A': array([2., 0., 0., 0., 0., 0., 0., 0.]),
 '-': array([0., 0., 1., 0., 0., 0., 2., 2.])}

In [66]:
m = alignment.substitutions
print(m)

    A   C   G   T
A 1.0 0.0 0.0 0.0
C 2.0 0.0 0.0 0.0
G 0.0 0.0 4.0 0.0
T 0.0 0.0 0.0 9.0



In [67]:
m["C", "A"]

2.0

In [68]:
m["A", "C"]

0.0

In [69]:
m += m.transpose()
m /= 2.0
print(m)

    A   C   G   T
A 1.0 1.0 0.0 0.0
C 1.0 0.0 0.0 0.0
G 0.0 0.0 4.0 0.0
T 0.0 0.0 0.0 9.0



In [70]:
m["A", "C"]

1.0

In [71]:
m["C", "A"]

1.0

In [72]:
align_array = np.array(alignment)
align_array.shape

(3, 8)

In [73]:
align_array

array([[b'C', b'G', b'G', b'T', b'T', b'T', b'T', b'T'],
       [b'A', b'G', b'-', b'T', b'T', b'T', b'-', b'-'],
       [b'A', b'G', b'G', b'T', b'T', b'T', b'-', b'-']], dtype='|S1')

In [75]:
align_array = np.array(alignment, dtype="U")
print(align_array.shape)
print(align_array)

(3, 8)
[['C' 'G' 'G' 'T' 'T' 'T' 'T' 'T']
 ['A' 'G' '-' 'T' 'T' 'T' '-' '-']
 ['A' 'G' 'G' 'T' 'T' 'T' '-' '-']]


In [76]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [77]:
alignment.sort()
print(alignment)

                  0 AGGTTT-- 6
                  0 AG-TTT-- 5
                  1 CGGTTTTT 9



In [78]:
from Bio.SeqUtils import gc_fraction
alignment.sort(key=gc_fraction)
print(alignment)

                  0 AG-TTT-- 5
                  0 AGGTTT-- 6
                  1 CGGTTTTT 9



In [79]:
alignment.sort(key=gc_fraction, reverse=True)
print(alignment)

                  1 CGGTTTTT 9
                  0 AGGTTT-- 6
                  0 AG-TTT-- 5



In [80]:
alignment.sequences

['CCGGTTTTT', 'AGGTTT', 'AGTTTAA']

In [81]:
rc_alignment = alignment.reverse_complement()
print(rc_alignment.sequences)

['AAAAACCGG', 'AAACCT', 'TTAAACT']


In [82]:
print(rc_alignment)

                  0 AAAAACCG 8
                  0 --AAACCT 6
                  2 --AAA-CT 7



In [83]:
alignment[:, :4].sequences

['CCGGTTTTT', 'AGGTTT', 'AGTTTAA']

In [84]:
print(alignment[:, :4])

                  1 CGGT 5
                  0 AGGT 4
                  0 AG-T 3



In [85]:
rc_alignment = alignment[:, :4].reverse_complement()
rc_alignment[:, :4].sequences

['AAAAACCGG', 'AAACCT', 'TTAAACT']

In [86]:
print(rc_alignment[:, :4])

                  4 ACCG 8
                  2 ACCT 6
                  4 A-CT 7



In [87]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
a1 = SeqRecord(Seq("AAAAC"), id="Alpha")
b1 = SeqRecord(Seq("AAAC"), id="Beta")
c1 = SeqRecord(Seq("AAAAG"), id="Gamma")
a2 = SeqRecord(Seq("GTT"), id="Alpha")
b2 = SeqRecord(Seq("TT"), id="Beta")
c2 = SeqRecord(Seq("GT"), id="Gamma")
left = Alignment(
    [a1, b1, c1], coordinates=np.array([[0, 3, 4, 5], [0, 3, 3, 4], [0, 3, 4, 5]])
)
left.annotations = {"tool": "demo", "name": "start"}
left.column_annotations = {"stats": "CCCXC"}
right = Alignment(
    [a2, b2, c2], coordinates=np.array([[0, 1, 2, 3], [0, 0, 1, 2], [0, 1, 1, 2]])
)
right.annotations = {"tool": "demo", "name": "end"}
right.column_annotations = {"stats": "CXC"}

In [88]:
print(left)

Alpha             0 AAAAC 5
Beta              0 AAA-C 4
Gamma             0 AAAAG 5



In [89]:
print(right)

Alpha             0 GTT 3
Beta              0 -TT 2
Gamma             0 G-T 2



In [90]:
combined = left + right
print(combined)

Alpha             0 AAAACGTT 8
Beta              0 AAA-C-TT 6
Gamma             0 AAAAGG-T 7



In [91]:
len(right)

3

In [92]:
len(left)

3

In [93]:
len(combined)

3

In [94]:
combined.annotations

{'tool': 'demo'}

In [95]:
combined.column_annotations

{'stats': 'CCCXCCXC'}

In [96]:
chromosome = "AAAAAAAACCCCCCCAAAAAAAAAAAGGGGGGAAAAAAAA"
transcript = "CCCCCCCGGGGGG"
sequences1 = [chromosome, transcript]
coordinates1 = np.array([[8, 15, 26, 32], [0, 7, 7, 13]])
alignment1 = Alignment(sequences1, coordinates1)
print(alignment1)

target            8 CCCCCCCAAAAAAAAAAAGGGGGG 32
                  0 |||||||-----------|||||| 24
query             0 CCCCCCC-----------GGGGGG 13



In [97]:
rnaseq = "CCCCGGGG"
sequences2 = [transcript, rnaseq]
coordinates2 = np.array([[3, 11], [0, 8]])
alignment2 = Alignment(sequences2, coordinates2)
print(alignment2)

target            3 CCCCGGGG 11
                  0 ||||||||  8
query             0 CCCCGGGG  8



In [98]:
alignment3 = alignment1.map(alignment2)
print(alignment3)

target           11 CCCCAAAAAAAAAAAGGGG 30
                  0 ||||-----------|||| 19
query             0 CCCC-----------GGGG  8



In [99]:
print(alignment3.coordinates)

[[11 15 26 30]
 [ 0  4  4  8]]


In [100]:
format(alignment3, "psl")

'8\t0\t0\t0\t0\t0\t1\t11\t+\tquery\t8\t0\t8\ttarget\t40\t11\t30\t2\t4,4,\t0,4,\t11,26,\n'