In [527]:
seqA = "CCGGTTTTT"
seqB = "AGTTTAA"
seqC = "AGGTTT"
sequences = [seqA, seqB, seqC]
print(sequences)

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']


In [528]:
import numpy as np
coordinates = np.array([[1, 3, 4, 7, 9], [0, 2, 2, 5, 5], [0, 2, 3, 6, 6]])
print(coordinates)

[[1 3 4 7 9]
 [0 2 2 5 5]
 [0 2 3 6 6]]


In [529]:
from Bio.Align import Alignment
alignment = Alignment(sequences, coordinates)
alignment 

<Alignment object (3 rows x 8 columns) at 0x10aa36c70>

In [530]:
alignment.sequences

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']

In [531]:
alignment.coordinates

array([[1, 3, 4, 7, 9],
       [0, 2, 2, 5, 5],
       [0, 2, 3, 6, 6]])

In [532]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [533]:
lines = ["CGGTTTTT", "AG-TTT--", "AGGTTT--"]
for line in lines:
    print(line)

CGGTTTTT
AG-TTT--
AGGTTT--


In [534]:
lines = [line.encode() for line in lines]  # convert to bytes
lines

[b'CGGTTTTT', b'AG-TTT--', b'AGGTTT--']

In [535]:
sequences, coordinates = Alignment.parse_printed_alignment(lines)
sequences

[b'CGGTTTTT', b'AGTTT', b'AGGTTT']

In [536]:
sequences = [sequence.decode() for sequence in sequences]
sequences

['CGGTTTTT', 'AGTTT', 'AGGTTT']

In [537]:
print(coordinates)

[[0 2 3 6 8]
 [0 2 2 5 5]
 [0 2 3 6 6]]


In [538]:
from Bio.Seq import Seq
sequences[0] = "C" + sequences[0]
sequences[1] = sequences[1] + "AA"
sequences

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']

In [539]:
coordinates[0, :] += 1
print(coordinates)

[[1 3 4 7 9]
 [0 2 2 5 5]
 [0 2 3 6 6]]


In [540]:
alignment = Alignment(sequences, coordinates)
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [541]:
ungapped_alignment = Alignment(["ACGTACGT", "AAGTACGT", "ACGTACCT"])
ungapped_alignment  

<Alignment object (3 rows x 8 columns) at 0x10ab20910>

In [542]:
print(ungapped_alignment.coordinates)

[[0 8]
 [0 8]
 [0 8]]


In [543]:
print(ungapped_alignment)

                  0 ACGTACGT 8
                  0 AAGTACGT 8
                  0 ACGTACCT 8



In [544]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [545]:
alignment.length

8

In [546]:
alignment[0]

'CGGTTTTT'

In [547]:
alignment[1]

'AG-TTT--'

In [548]:
alignment[2]

'AGGTTT--'

In [549]:
alignment[0, :]

'CGGTTTTT'

In [550]:
alignment[1, :]

'AG-TTT--'

In [551]:
alignment[0, 1:-1]

'GGTTTT'

In [552]:
alignment[1, 1:-1]

'G-TTT-'

In [553]:
alignment[0, (1, 2, 4)]

'GGT'

In [554]:
alignment[1, range(0, 5, 2)]

'A-T'

In [555]:
alignment[0, 2]

'G'

In [556]:
alignment[2, 6]

'-'

In [557]:
alignment[:, 0]

'CAA'

In [558]:
alignment[:, 1]

'GGG'

In [559]:
alignment[:, 2]

'G-G'

In [560]:
alignment[1:]

<Alignment object (2 rows x 6 columns) at 0x10aafa3a0>

In [561]:
print(alignment[1:])

target            0 AG-TTT 5
                  0 ||-||| 6
query             0 AGGTTT 6



In [562]:
alignment[:, :4] 

<Alignment object (3 rows x 4 columns) at 0x10ab209a0>

In [563]:
print(alignment[:, :4])

                  1 CGGT 5
                  0 AG-T 3
                  0 AGGT 4



In [564]:
alignment[:, -6:] 

<Alignment object (3 rows x 6 columns) at 0x10aa36df0>

In [565]:
print(alignment[:, -6:])

                  3 GTTTTT 9
                  2 -TTT-- 5
                  2 GTTT-- 6



In [566]:
print(alignment[:, (1, 3, 0)])

                  0 GTC 3
                  0 GTA 3
                  0 GTA 3



In [567]:
len(alignment)

3

In [568]:
alignment.length

8

In [569]:
alignment.shape

(3, 8)

In [570]:
pairwise_alignment = alignment[:2, :]
print(pairwise_alignment)

target            1 CGGTTTTT 9
                  0 .|-|||-- 8
query             0 AG-TTT-- 5



In [571]:
print(pairwise_alignment.aligned)

[[[1 3]
  [4 7]]

 [[0 2]
  [2 5]]]


In [572]:
pairwise_alignment1 = Alignment(["AAACAAA", "AAAGAAA"],
                                np.array([[0, 3, 4, 4, 7], [0, 3, 3, 4, 7]]))  # fmt: skip

pairwise_alignment2 = Alignment(["AAACAAA", "AAAGAAA"],
                                np.array([[0, 3, 3, 4, 7], [0, 3, 4, 4, 7]]))  # fmt: skip

print(pairwise_alignment1)

target            0 AAAC-AAA 7
                  0 |||--||| 8
query             0 AAA-GAAA 7



In [573]:
print(pairwise_alignment2)

target            0 AAA-CAAA 7
                  0 |||--||| 8
query             0 AAAG-AAA 7



In [574]:
pairwise_alignment1.aligned

array([[[0, 3],
        [4, 7]],

       [[0, 3],
        [4, 7]]])

In [575]:
pairwise_alignment2.aligned

array([[[0, 3],
        [4, 7]],

       [[0, 3],
        [4, 7]]])

In [576]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [577]:
alignment.indices

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 0,  1, -1,  2,  3,  4, -1, -1],
       [ 0,  1,  2,  3,  4,  5, -1, -1]])

In [578]:
alignment.sequences

['CCGGTTTTT', 'AGTTTAA', 'AGGTTT']

In [579]:
alignment.inverse_indices  

[array([-1,  0,  1,  2,  3,  4,  5,  6,  7]),
 array([ 0,  1,  3,  4,  5, -1, -1]),
 array([0, 1, 2, 3, 4, 5])]

In [580]:
print(pairwise_alignment)

target            1 CGGTTTTT 9
                  0 .|-|||-- 8
query             0 AG-TTT-- 5



In [581]:
pairwise_alignment.counts()

AlignmentCounts(gaps=3, identities=4, mismatches=1)

In [582]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [583]:
alignment.counts()

AlignmentCounts(gaps=8, identities=14, mismatches=2)

In [584]:
alignment.frequencies

{'C': array([1., 0., 0., 0., 0., 0., 0., 0.]),
 'G': array([0., 3., 2., 0., 0., 0., 0., 0.]),
 'T': array([0., 0., 0., 3., 3., 3., 1., 1.]),
 'A': array([2., 0., 0., 0., 0., 0., 0., 0.]),
 '-': array([0., 0., 1., 0., 0., 0., 2., 2.])}

In [585]:
m = alignment.substitutions
print(m)

    A   C   G   T
A 1.0 0.0 0.0 0.0
C 2.0 0.0 0.0 0.0
G 0.0 0.0 4.0 0.0
T 0.0 0.0 0.0 9.0



In [586]:
m["C", "A"]

2.0

In [587]:
m["A", "C"]

0.0

In [588]:
m += m.transpose()
m /= 2.0
print(m)

    A   C   G   T
A 1.0 1.0 0.0 0.0
C 1.0 0.0 0.0 0.0
G 0.0 0.0 4.0 0.0
T 0.0 0.0 0.0 9.0



In [589]:
m["A", "C"]

1.0

In [590]:
m["C", "A"]

1.0

In [591]:
align_array = np.array(alignment)
align_array.shape

(3, 8)

In [592]:
align_array

array([[b'C', b'G', b'G', b'T', b'T', b'T', b'T', b'T'],
       [b'A', b'G', b'-', b'T', b'T', b'T', b'-', b'-'],
       [b'A', b'G', b'G', b'T', b'T', b'T', b'-', b'-']], dtype='|S1')

In [593]:
align_array = np.array(alignment, dtype="U")
print(align_array.shape)
print(align_array)

(3, 8)
[['C' 'G' 'G' 'T' 'T' 'T' 'T' 'T']
 ['A' 'G' '-' 'T' 'T' 'T' '-' '-']
 ['A' 'G' 'G' 'T' 'T' 'T' '-' '-']]


In [594]:
print(alignment)

                  1 CGGTTTTT 9
                  0 AG-TTT-- 5
                  0 AGGTTT-- 6



In [595]:
alignment.sort()
print(alignment)

                  0 AGGTTT-- 6
                  0 AG-TTT-- 5
                  1 CGGTTTTT 9



In [596]:
from Bio.SeqUtils import gc_fraction
alignment.sort(key=gc_fraction)
print(alignment)

                  0 AG-TTT-- 5
                  0 AGGTTT-- 6
                  1 CGGTTTTT 9



In [597]:
alignment.sort(key=gc_fraction, reverse=True)
print(alignment)

                  1 CGGTTTTT 9
                  0 AGGTTT-- 6
                  0 AG-TTT-- 5



In [598]:
alignment.sequences

['CCGGTTTTT', 'AGGTTT', 'AGTTTAA']

In [599]:
rc_alignment = alignment.reverse_complement()
print(rc_alignment.sequences)

['AAAAACCGG', 'AAACCT', 'TTAAACT']


In [600]:
print(rc_alignment)

                  0 AAAAACCG 8
                  0 --AAACCT 6
                  2 --AAA-CT 7



In [601]:
alignment[:, :4].sequences

['CCGGTTTTT', 'AGGTTT', 'AGTTTAA']

In [602]:
print(alignment[:, :4])

                  1 CGGT 5
                  0 AGGT 4
                  0 AG-T 3



In [603]:
rc_alignment = alignment[:, :4].reverse_complement()
rc_alignment[:, :4].sequences

['AAAAACCGG', 'AAACCT', 'TTAAACT']

In [604]:
print(rc_alignment[:, :4])

                  4 ACCG 8
                  2 ACCT 6
                  4 A-CT 7



In [605]:
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
a1 = SeqRecord(Seq("AAAAC"), id="Alpha")
b1 = SeqRecord(Seq("AAAC"), id="Beta")
c1 = SeqRecord(Seq("AAAAG"), id="Gamma")
a2 = SeqRecord(Seq("GTT"), id="Alpha")
b2 = SeqRecord(Seq("TT"), id="Beta")
c2 = SeqRecord(Seq("GT"), id="Gamma")
left = Alignment(
    [a1, b1, c1], coordinates=np.array([[0, 3, 4, 5], [0, 3, 3, 4], [0, 3, 4, 5]])
)
left.annotations = {"tool": "demo", "name": "start"}
left.column_annotations = {"stats": "CCCXC"}
right = Alignment(
    [a2, b2, c2], coordinates=np.array([[0, 1, 2, 3], [0, 0, 1, 2], [0, 1, 1, 2]])
)
right.annotations = {"tool": "demo", "name": "end"}
right.column_annotations = {"stats": "CXC"}

In [606]:
print(left)

Alpha             0 AAAAC 5
Beta              0 AAA-C 4
Gamma             0 AAAAG 5



In [607]:
print(right)

Alpha             0 GTT 3
Beta              0 -TT 2
Gamma             0 G-T 2



In [608]:
combined = left + right
print(combined)

Alpha             0 AAAACGTT 8
Beta              0 AAA-C-TT 6
Gamma             0 AAAAGG-T 7



In [609]:
len(right)

3

In [610]:
len(left)

3

In [611]:
len(combined)

3

In [612]:
combined.annotations

{'tool': 'demo'}

In [613]:
combined.column_annotations

{'stats': 'CCCXCCXC'}

In [614]:
chromosome = "AAAAAAAACCCCCCCAAAAAAAAAAAGGGGGGAAAAAAAA"
transcript = "CCCCCCCGGGGGG"
sequences1 = [chromosome, transcript]
coordinates1 = np.array([[8, 15, 26, 32], [0, 7, 7, 13]])
alignment1 = Alignment(sequences1, coordinates1)
print(alignment1)

target            8 CCCCCCCAAAAAAAAAAAGGGGGG 32
                  0 |||||||-----------|||||| 24
query             0 CCCCCCC-----------GGGGGG 13



In [615]:
rnaseq = "CCCCGGGG"
sequences2 = [transcript, rnaseq]
coordinates2 = np.array([[3, 11], [0, 8]])
alignment2 = Alignment(sequences2, coordinates2)
print(alignment2)

target            3 CCCCGGGG 11
                  0 ||||||||  8
query             0 CCCCGGGG  8



In [616]:
alignment3 = alignment1.map(alignment2)
print(alignment3)

target           11 CCCCAAAAAAAAAAAGGGG 30
                  0 ||||-----------|||| 19
query             0 CCCC-----------GGGG  8



In [617]:
print(alignment3.coordinates)

[[11 15 26 30]
 [ 0  4  4  8]]


In [618]:
format(alignment3, "psl")

'8\t0\t0\t0\t0\t0\t1\t11\t+\tquery\t8\t0\t8\ttarget\t40\t11\t30\t2\t4,4,\t0,4,\t11,26,\n'

In [619]:
from Bio import Align
chain = Align.read("/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/panTro5ToPanTro6.over.chain", "chain")
chain.sequences[0].id

'chr1'

In [620]:
len(chain.sequences[0].seq)

228573443

In [621]:
chain.sequences[1].id

'chr1'

In [622]:
len(chain.sequences[1].seq)

224244399

In [623]:
import numpy as np
np.set_printoptions(threshold=5)  # print 5 array elements per row
print(chain.coordinates)

[[122250000 122250400 122250400 ... 122909818 122909819 122909835]
 [111776384 111776784 111776785 ... 112019962 112019962 112019978]]


In [624]:
transcript = Align.read("/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/est.panTro5.psl", "psl")
transcript.sequences[0].id

'chr1'

In [625]:
len(transcript.sequences[0].seq)

228573443

In [626]:
transcript.sequences[1].id

'DC525629'

In [627]:
len(transcript.sequences[1].seq)

407

In [628]:
print(transcript.coordinates)

[[122835789 122835847 122840993 122841145 122907212 122907314]
 [       32        90        90       242       242       344]]


In [629]:
len(chain.sequences[0].seq) == len(transcript.sequences[0].seq)

True

In [630]:
chain = chain[::-1]
chain.sequences[0].id

'chr1'

In [631]:
len(chain.sequences[0].seq)

224244399

In [632]:
chain.sequences[1].id

'chr1'

In [633]:
len(chain.sequences[1].seq)

228573443

In [634]:
print(chain.coordinates) 

[[111776384 111776784 111776785 ... 112019962 112019962 112019978]
 [122250000 122250400 122250400 ... 122909818 122909819 122909835]]


In [635]:
np.set_printoptions(threshold=1000)  # reset the print options

In [636]:
lifted_transcript = chain.map(transcript)
lifted_transcript.sequences[0].id

'chr1'

In [637]:
len(lifted_transcript.sequences[0].seq)

224244399

In [638]:
lifted_transcript.sequences[1].id

'DC525629'

In [639]:
len(lifted_transcript.sequences[1].seq)

407

In [640]:
print(lifted_transcript.coordinates)

[[111982717 111982775 111987921 111988073 112009200 112009302]
 [       32        90        90       242       242       344]]


In [641]:
from Bio import Align
path = "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/panTro5.maf"
genome_alignment = Align.read(path, "maf")
for record in genome_alignment.sequences:
    print(record.id, len(record.seq))

panTro5.chr1 228573443
hg19.chr1 249250621
rheMac8.chr1 225584828
calJac3.chr18 47448759
mm10.chr3 160039680
rn6.chr2 266435125


In [642]:
print(genome_alignment.coordinates)

[[133922962 133922962 133922970 133922970 133922972 133922972 133922995
  133922998 133923010]
 [155784573 155784573 155784581 155784581 155784583 155784583 155784606
  155784609 155784621]
 [130383910 130383910 130383918 130383918 130383920 130383920 130383943
  130383946 130383958]
 [  9790455   9790455   9790463   9790463   9790465   9790465   9790488
    9790491   9790503]
 [ 88858039  88858036  88858028  88858026  88858024  88858020  88857997
   88857997  88857985]
 [188162970 188162967 188162959 188162959 188162957 188162953 188162930
  188162930 188162918]]


In [643]:
print(genome_alignment)

panTro5.c 133922962 ---ACTAGTTA--CA----GTAACAGAAAATAAAATTTAAATAGAAACTTAAAggcc
hg19.chr1 155784573 ---ACTAGTTA--CA----GTAACAGAAAATAAAATTTAAATAGAAACTTAAAggcc
rheMac8.c 130383910 ---ACTAGTTA--CA----GTAACAGAAAATAAAATTTAAATAGAAACTTAAAggcc
calJac3.c   9790455 ---ACTAGTTA--CA----GTAACAGAAAATAAAATTTAAATAGAAGCTTAAAggct
mm10.chr3  88858039 TATAATAATTGTATATGTCACAGAAAAAAATGAATTTTCAAT---GACTTAATAGCC
rn6.chr2  188162970 TACAATAATTG--TATGTCATAGAAAAAAATGAATTTTCAAT---AACTTAATAGCC

panTro5.c 133923010
hg19.chr1 155784621
rheMac8.c 130383958
calJac3.c   9790503
mm10.chr3  88857985
rn6.chr2  188162918



In [644]:
paths = [
    "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/panTro5ToPanTro6.chain",
    "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/hg19ToHg38.chain",
    "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/rheMac8ToRheMac10.chain",
    "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/calJac3ToCalJac4.chain",
    "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/mm10ToMm39.chain",
    "/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/rn6ToRn7.chain",
]
liftover_alignments = [Align.read(path, "chain") for path in paths]
for liftover_alignment in liftover_alignments:
    print(liftover_alignment.target.id, liftover_alignment.coordinates[0, :])


chr1 [133919957 133924947 133924947 133926309 133926312 133932620]
chr1 [155184381 156354347 156354348 157128497 157128497 157137496]
chr1 [130382477 130383872 130383872 130384222 130384222 130388520]
chr18 [9786631 9787941 9788508 9788508 9795062 9795065 9795737]
chr3 [66807541 74196805 74196831 94707528 94707528 94708176 94708178 94708718]
chr2 [188111581 188158351 188158351 188171225 188171225 188228261 188228261
 188236997]


In [645]:
genome_alignment = genome_alignment.mapall(liftover_alignments)
for record in genome_alignment.sequences:
    print(record.id, len(record.seq))

chr1 224244399
chr1 248956422
chr1 223616942
chr18 47031477
chr3 159745316
chr2 249053267


In [646]:
print(genome_alignment.coordinates)

[[130611000 130611000 130611008 130611008 130611010 130611010 130611033
  130611036 130611048]
 [155814782 155814782 155814790 155814790 155814792 155814792 155814815
  155814818 155814830]
 [ 95186253  95186253  95186245  95186245  95186243  95186243  95186220
   95186217  95186205]
 [  9758318   9758318   9758326   9758326   9758328   9758328   9758351
    9758354   9758366]
 [ 88765346  88765343  88765335  88765333  88765331  88765327  88765304
   88765304  88765292]
 [174256702 174256699 174256691 174256691 174256689 174256685 174256662
  174256662 174256650]]


In [7]:
from Bio import SeqIO
names = ("panTro6", "hg38", "rheMac10", "calJac4", "mm39", "rn7")
for i, name in enumerate(names):
    filename = f"/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/{name}.2bit"
    genome = SeqIO.parse(filename, "twobit")
    chromosome = genome_alignment.sequences[i].id
    assert len(genome_alignment.sequences[i]) == len(genome[chromosome])
    genome_alignment.sequences[i] = genome[chromosome]
    genome_alignment.sequences[i].id = f"{name}.{chromosome}"

print(genome_alignment)

ValueError: Unknown signature

In [4]:
from Bio import SeqIO
names = ("panTro6", "hg38", "rheMac10", "calJac4", "mm39", "rn7")
for i, name in enumerate(names):
    filename = f"/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/{name}.2bit"
    genome = SeqIO.parse(filename, "twobit")
    chromosome = genome_alignment.sequences[i].id
    assert len(genome_alignment.sequences[i]) == len(genome[chromosome])
    genome_alignment.sequences[i] = genome[chromosome]
    genome_alignment.sequences[i].id = f"{name}.{chromosome}"

print(genome_alignment)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/panTro6.2bit'

In [ ]:
alignment_list = [alignment1, alignment2, alignment3]
alignment_iterator1 = iter(alignment_list)
alignment_iterator2 = iter(alignment_list)
next(alignment_iterator1)

<Alignment object (2 rows x 24 columns) at 0x10a5675e0>

In [ ]:
next(alignment_iterator2)

<Alignment object (2 rows x 24 columns) at 0x10a5675e0>

In [ ]:
next(alignment_iterator1)

<Alignment object (2 rows x 8 columns) at 0x10a567820>

In [ ]:
next(alignment_iterator1)

<Alignment object (2 rows x 19 columns) at 0x10a63a580>

In [ ]:
next(alignment_iterator2)

<Alignment object (2 rows x 8 columns) at 0x10a567820>

In [ ]:
next(alignment_iterator2)

<Alignment object (2 rows x 19 columns) at 0x10a63a580>

In [ ]:
from Bio.Align import Alignments
alignments = Alignments([alignment1, alignment2, alignment3])
alignment_iterator1 = iter(alignments)
alignment_iterator2 = iter(alignments)
alignment_iterator1 is alignment_iterator2

True

In [ ]:
next(alignment_iterator1)

<Alignment object (2 rows x 24 columns) at 0x10a5675e0>

In [ ]:
next(alignment_iterator2)

<Alignment object (2 rows x 8 columns) at 0x10a567820>

In [ ]:
next(alignment_iterator1)

<Alignment object (2 rows x 19 columns) at 0x10a63a580>

In [ ]:
for item in alignments:
    print(repr(item))  

<Alignment object (2 rows x 24 columns) at 0x10a5675e0>
<Alignment object (2 rows x 8 columns) at 0x10a567820>
<Alignment object (2 rows x 19 columns) at 0x10a63a580>


In [ ]:
for item in alignments:
    print(repr(item))  

<Alignment object (2 rows x 24 columns) at 0x10a5675e0>
<Alignment object (2 rows x 8 columns) at 0x10a567820>
<Alignment object (2 rows x 19 columns) at 0x10a63a580>


In [ ]:
alignments.score = 100
alignments.score

100

In [ ]:
from Bio import Align
alignments = Align.parse("/Users/shlomohajizadeh/Documents/GitHub/Bioinformatics/Biopython(own)/ucsc_mm9_chr10.maf", "maf")
alignments

In [ ]:
alignments.metadata

{'MAF Version': '1', 'Scoring': 'autoMZ.v1'}

In [ ]:
for a in alignments:
    print(len(a.sequences))

2
4
5
6
7
7
1
4
1
5
6
4
1
9
10
7
1
3
1
4
3
5
1
2
2
1
2
3
6
5
1
2
7
10
1
4
1
9
10
11
12
13
14
15
15
14
7
6


In [ ]:
len(alignments)

48

In [ ]:
alignment_list = list(alignments)
len(alignment_list)

48

In [ ]:
alignment_list[27]

<Alignment object (3 rows x 91 columns) at 0x10a715790>

In [ ]:
print(alignment_list[27])

mm9.chr10   3019377 CCCCAGCATTCTGGCAGACACAGTG-AAAAGAGACAGATGGTCACTAATAAAATCTGT-A
felCat3.s     46845 CCCAAGTGTTCTGATAGCTAATGTGAAAAAGAAGCATGTGCCCACCAGTAAGCTTTGTGG
canFam2.c  47545247 CCCAAGTGTTCTGATTGCCTCTGTGAAAAAGAAACATGGGCCCGCTAATAagatttgcaa

mm9.chr10   3019435 TAAATTAG-ATCTCAGAGGATGGATGGACCA  3019465
felCat3.s     46785 TGAACTAGAATCTCAGAGGATG---GGACTC    46757
canFam2.c  47545187 tgacctagaatctcagaggatg---ggactc 47545159



In [ ]:
type(alignments)

Bio.Align.maf.AlignmentIterator

In [ ]:
alignments = alignments[:]
print(alignments)

[<Alignment object (2 rows x 164 columns) at 0x10a574a90>, <Alignment object (4 rows x 466 columns) at 0x10a79f550>, <Alignment object (5 rows x 127 columns) at 0x10a79f880>, <Alignment object (6 rows x 278 columns) at 0x10a79fd00>, <Alignment object (7 rows x 175 columns) at 0x10a7ab220>, <Alignment object (7 rows x 254 columns) at 0x10a7ab7f0>, <Alignment object (1 rows x 219 columns) at 0x10a7abd60>, <Alignment object (4 rows x 166 columns) at 0x10a7b7100>, <Alignment object (1 rows x 1041 columns) at 0x10a7b7520>, <Alignment object (5 rows x 48 columns) at 0x10a7b7970>, <Alignment object (6 rows x 54 columns) at 0x10a7b7ee0>, <Alignment object (4 rows x 36 columns) at 0x10a7bf520>, <Alignment object (1 rows x 17 columns) at 0x10a7bfa00>, <Alignment object (9 rows x 64 columns) at 0x10a7bff40>, <Alignment object (10 rows x 253 columns) at 0x10a7ca640>, <Alignment object (7 rows x 72 columns) at 0x10a7cae80>, <Alignment object (1 rows x 2572 columns) at 0x10a7d35b0>, <Alignment objec

In [ ]:
len(alignments)

48

In [ ]:
print(alignments[3-47])
print(alignments.metadata)

mm9.chr10   3012828 TTTGCATAGACTCTCTTGGCAACAAAATAACGTTATATTTAAACATCCATTAAAATAATG
cavPor2.s     39417 -----GTGGGATGTCTTGACAGCTAAATAGTcttatatttaagcatttatGAAAATAATG
otoGar1.s    178634 -----GTGGACATTCGTGACAGGCAAATAGTGTTCTATTTAAACATTTGTTGAAATGATA
ponAbe2.c 158049472 -----GTGGACTATCCTGACAACCAAATAGCGTTATATTTAAACATTTATGAAAATAATA
panTro2.c 157528852 -----GCGGACTATCTTGACAACCAAATAGCGTTATATTTAAACGTTTATGAAAATAATA
hg18.chr6 155038780 -----GTGGACTATCTTGACAACCAAATAGCGTTATATTTAAACGTTTGTGAAAATAATA
echTel1.s     87492 TTGGGGTGGATGCTCTTGGCAGTCACACAGTGCTCTATTTTAGGATTTACTAGAACAATG

mm9.chr10   3012888 CACTTAGCACAGCCTGCCCTGAGGGAT----GAACACT--ATTGTTAA-AGAACTATTCC
cavPor2.s     39362 AGGTTATCATGGTTCGCTCTAGTAGCTCTGAGACCTTT--ATTGTCAGCAAAGCTGTTTA
otoGar1.s    178579 AACTTAGCTCAGCC--CCTT---AGAAGTG-AGAGGCT--ACTGTCAGGGAAGCGGTTTT
ponAbe2.c 158049417 AGCTTAGCATAACCTGCCTTGACAGATGTG-GTATGC-------CTAGTGAAGTTGTTTA
panTro2.c 157528797 AGCTTAGCATAACCTGCCTTGACAGATGTG-GTATGC-------CTAGTGAAGTTGCTTA
hg18.chr6 155038725 AGCTTAG

In [ ]:
from Bio import Align
target = "myfile.txt"
Align.write(alignments, target, "clustal")

48

In [ ]:
from Bio import Align
alignments = Align.Alignments(alignments)
metadata = {"Program": "Biopython", "Version": "1.81"}
alignments.metadata = metadata
target = "myfile.txt"
Align.write(alignments, target, "clustal")
print(alignments)

[<Alignment object (2 rows x 164 columns) at 0x10a574a90>, <Alignment object (4 rows x 466 columns) at 0x10a79f550>, <Alignment object (5 rows x 127 columns) at 0x10a79f880>, <Alignment object (6 rows x 278 columns) at 0x10a79fd00>, <Alignment object (7 rows x 175 columns) at 0x10a7ab220>, <Alignment object (7 rows x 254 columns) at 0x10a7ab7f0>, <Alignment object (1 rows x 219 columns) at 0x10a7abd60>, <Alignment object (4 rows x 166 columns) at 0x10a7b7100>, <Alignment object (1 rows x 1041 columns) at 0x10a7b7520>, <Alignment object (5 rows x 48 columns) at 0x10a7b7970>, <Alignment object (6 rows x 54 columns) at 0x10a7b7ee0>, <Alignment object (4 rows x 36 columns) at 0x10a7bf520>, <Alignment object (1 rows x 17 columns) at 0x10a7bfa00>, <Alignment object (9 rows x 64 columns) at 0x10a7bff40>, <Alignment object (10 rows x 253 columns) at 0x10a7ca640>, <Alignment object (7 rows x 72 columns) at 0x10a7cae80>, <Alignment object (1 rows x 2572 columns) at 0x10a7d35b0>, <Alignment objec

In [ ]:
str(alignments)

'[<Alignment object (2 rows x 164 columns) at 0x10a574a90>, <Alignment object (4 rows x 466 columns) at 0x10a79f550>, <Alignment object (5 rows x 127 columns) at 0x10a79f880>, <Alignment object (6 rows x 278 columns) at 0x10a79fd00>, <Alignment object (7 rows x 175 columns) at 0x10a7ab220>, <Alignment object (7 rows x 254 columns) at 0x10a7ab7f0>, <Alignment object (1 rows x 219 columns) at 0x10a7abd60>, <Alignment object (4 rows x 166 columns) at 0x10a7b7100>, <Alignment object (1 rows x 1041 columns) at 0x10a7b7520>, <Alignment object (5 rows x 48 columns) at 0x10a7b7970>, <Alignment object (6 rows x 54 columns) at 0x10a7b7ee0>, <Alignment object (4 rows x 36 columns) at 0x10a7bf520>, <Alignment object (1 rows x 17 columns) at 0x10a7bfa00>, <Alignment object (9 rows x 64 columns) at 0x10a7bff40>, <Alignment object (10 rows x 253 columns) at 0x10a7ca640>, <Alignment object (7 rows x 72 columns) at 0x10a7cae80>, <Alignment object (1 rows x 2572 columns) at 0x10a7d35b0>, <Alignment obje

In [ ]:
format(alignments)

'[<Alignment object (2 rows x 164 columns) at 0x10a574a90>, <Alignment object (4 rows x 466 columns) at 0x10a79f550>, <Alignment object (5 rows x 127 columns) at 0x10a79f880>, <Alignment object (6 rows x 278 columns) at 0x10a79fd00>, <Alignment object (7 rows x 175 columns) at 0x10a7ab220>, <Alignment object (7 rows x 254 columns) at 0x10a7ab7f0>, <Alignment object (1 rows x 219 columns) at 0x10a7abd60>, <Alignment object (4 rows x 166 columns) at 0x10a7b7100>, <Alignment object (1 rows x 1041 columns) at 0x10a7b7520>, <Alignment object (5 rows x 48 columns) at 0x10a7b7970>, <Alignment object (6 rows x 54 columns) at 0x10a7b7ee0>, <Alignment object (4 rows x 36 columns) at 0x10a7bf520>, <Alignment object (1 rows x 17 columns) at 0x10a7bfa00>, <Alignment object (9 rows x 64 columns) at 0x10a7bff40>, <Alignment object (10 rows x 253 columns) at 0x10a7ca640>, <Alignment object (7 rows x 72 columns) at 0x10a7cae80>, <Alignment object (1 rows x 2572 columns) at 0x10a7d35b0>, <Alignment obje

In [ ]:
print(format(alignments))

[<Alignment object (2 rows x 164 columns) at 0x10a574a90>, <Alignment object (4 rows x 466 columns) at 0x10a79f550>, <Alignment object (5 rows x 127 columns) at 0x10a79f880>, <Alignment object (6 rows x 278 columns) at 0x10a79fd00>, <Alignment object (7 rows x 175 columns) at 0x10a7ab220>, <Alignment object (7 rows x 254 columns) at 0x10a7ab7f0>, <Alignment object (1 rows x 219 columns) at 0x10a7abd60>, <Alignment object (4 rows x 166 columns) at 0x10a7b7100>, <Alignment object (1 rows x 1041 columns) at 0x10a7b7520>, <Alignment object (5 rows x 48 columns) at 0x10a7b7970>, <Alignment object (6 rows x 54 columns) at 0x10a7b7ee0>, <Alignment object (4 rows x 36 columns) at 0x10a7bf520>, <Alignment object (1 rows x 17 columns) at 0x10a7bfa00>, <Alignment object (9 rows x 64 columns) at 0x10a7bff40>, <Alignment object (10 rows x 253 columns) at 0x10a7ca640>, <Alignment object (7 rows x 72 columns) at 0x10a7cae80>, <Alignment object (1 rows x 2572 columns) at 0x10a7d35b0>, <Alignment objec

In [ ]:
print(pairwise_alignment2)

target            0 AAA-CAAA 7
                  0 |||--||| 8
query             0 AAAG-AAA 7



In [ ]:
print(format(pairwise_alignment, "bed"))

target	1	7	query	0	+	1	7	0	2	2,3,	0,3,



In [ ]:
print(pairwise_alignment.format("bed"))

target	1	7	query	0	+	1	7	0	2	2,3,	0,3,



In [ ]:
print(pairwise_alignment.format("bed", bedN=3))  

target	1	7



In [ ]:
print(pairwise_alignment.format("bed", bedN=6)) 

target	1	7	query	0	+



In [ ]:
from Bio import Align
alignment = Align.read("probcons.fa", "fasta")
alignment

<Alignment object (5 rows x 101 columns) at 0x10a85ed60>

In [ ]:
print(alignment)

plas_horv         0 D-VLLGANGGVLVFEPNDFSVKAGETITFKNNAGYPHNVVFDEDAVPSG-VD-VSKISQE
plas_chlr         0 --VKLGADSGALEFVPKTLTIKSGETVNFVNNAGFPHNIVFDEDAIPSG-VN-ADAISRD
plas_anav         0 --VKLGSDKGLLVFEPAKLTIKPGDTVEFLNNKVPPHNVVFDAALNPAKSADLAKSLSHK
plas_proh         0 VQIKMGTDKYAPLYEPKALSISAGDTVEFVMNKVGPHNVIFDK--VPAG-ES-APALSNT
azup_achc         0 VHMLNKGKDGAMVFEPASLKVAPGDTVTFIPTDK-GHNVETIKGMIPDG-AE-A------

plas_horv        57 EYLTAPGETFSVTLTV---PGTYGFYCEPHAGAGMVGKVTV 95
plas_chlr        56 DYLNAPGETYSVKLTA---AGEYGYYCEPHQGAGMVGKIIV 94
plas_anav        58 QLLMSPGQSTSTTFPADAPAGEYTFYCEPHRGAGMVGKITV 99
plas_proh        56 KLRIAPGSFYSVTLGT---PGTYSFYCTPHRGAGMVGTITV 94
azup_achc        51 -FKSKINENYKVTFTA---PGVYGVKCTPHYGMGMVGVVEV 88



In [ ]:
print(format(alignment, "fasta"))

>plas_horvu
D-VLLGANGGVLVFEPNDFSVKAGETITFKNNAGYPHNVVFDEDAVPSG-VD-VSKISQEEYLTAPGETFSVTLTV---PGTYGFYCEPHAGAGMVGKVTV
>plas_chlre
--VKLGADSGALEFVPKTLTIKSGETVNFVNNAGFPHNIVFDEDAIPSG-VN-ADAISRDDYLNAPGETYSVKLTA---AGEYGYYCEPHQGAGMVGKIIV
>plas_anava
--VKLGSDKGLLVFEPAKLTIKPGDTVEFLNNKVPPHNVVFDAALNPAKSADLAKSLSHKQLLMSPGQSTSTTFPADAPAGEYTFYCEPHRGAGMVGKITV
>plas_proho
VQIKMGTDKYAPLYEPKALSISAGDTVEFVMNKVGPHNVIFDK--VPAG-ES-APALSNTKLRIAPGSFYSVTLGT---PGTYSFYCTPHRGAGMVGTITV
>azup_achcy
VHMLNKGKDGAMVFEPASLKVAPGDTVTFIPTDK-GHNVETIKGMIPDG-AE-A-------FKSKINENYKVTFTA---PGVYGVKCTPHYGMGMVGVVEV



In [ ]:
print(format(alignment, "clustal"))

plas_horvu                          D-VLLGANGGVLVFEPNDFSVKAGETITFKNNAGYPHNVVFDEDAVPSG-
plas_chlre                          --VKLGADSGALEFVPKTLTIKSGETVNFVNNAGFPHNIVFDEDAIPSG-
plas_anava                          --VKLGSDKGLLVFEPAKLTIKPGDTVEFLNNKVPPHNVVFDAALNPAKS
plas_proho                          VQIKMGTDKYAPLYEPKALSISAGDTVEFVMNKVGPHNVIFDK--VPAG-
azup_achcy                          VHMLNKGKDGAMVFEPASLKVAPGDTVTFIPTDK-GHNVETIKGMIPDG-

plas_horvu                          VD-VSKISQEEYLTAPGETFSVTLTV---PGTYGFYCEPHAGAGMVGKVT
plas_chlre                          VN-ADAISRDDYLNAPGETYSVKLTA---AGEYGYYCEPHQGAGMVGKII
plas_anava                          ADLAKSLSHKQLLMSPGQSTSTTFPADAPAGEYTFYCEPHRGAGMVGKIT
plas_proho                          ES-APALSNTKLRIAPGSFYSVTLGT---PGTYSFYCTPHRGAGMVGTIT
azup_achcy                          AE-A-------FKSKINENYKVTFTA---PGVYGVKCTPHYGMGMVGVVE

plas_horvu                          V
plas_chlre                          V
plas_anava                          V
plas_proho    

In [ ]:
alignment.sequences

[SeqRecord(seq=Seq('DVLLGANGGVLVFEPNDFSVKAGETITFKNNAGYPHNVVFDEDAVPSGVDVSKI...VTV'), id='plas_horvu', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VKLGADSGALEFVPKTLTIKSGETVNFVNNAGFPHNIVFDEDAIPSGVNADAIS...IIV'), id='plas_chlre', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VKLGSDKGLLVFEPAKLTIKPGDTVEFLNNKVPPHNVVFDAALNPAKSADLAKS...ITV'), id='plas_anava', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VQIKMGTDKYAPLYEPKALSISAGDTVEFVMNKVGPHNVIFDKVPAGESAPALS...ITV'), id='plas_proho', name='<unknown name>', description='', dbxrefs=[]),
 SeqRecord(seq=Seq('VHMLNKGKDGAMVFEPASLKVAPGDTVTFIPTDKGHNVETIKGMIPDGAEAFKS...VEV'), id='azup_achcy', name='<unknown name>', description='', dbxrefs=[])]

In [ ]:
print(alignment.coordinates)

[[ 0  1  1 33 34 42 44 48 48 50 50 51 58 73 73 95]
 [ 0  0  0 32 33 41 43 47 47 49 49 50 57 72 72 94]
 [ 0  0  0 32 33 41 43 47 48 50 51 52 59 74 77 99]
 [ 0  1  2 34 35 43 43 47 47 49 49 50 57 72 72 94]
 [ 0  1  2 34 34 42 44 48 48 50 50 51 51 66 66 88]]


In [ ]:
from io import StringIO
stream = StringIO()
Align.write(alignment, stream, "FASTA")

1

In [ ]:
print(stream.getvalue())

>plas_horvu
D-VLLGANGGVLVFEPNDFSVKAGETITFKNNAGYPHNVVFDEDAVPSG-VD-VSKISQEEYLTAPGETFSVTLTV---PGTYGFYCEPHAGAGMVGKVTV
>plas_chlre
--VKLGADSGALEFVPKTLTIKSGETVNFVNNAGFPHNIVFDEDAIPSG-VN-ADAISRDDYLNAPGETYSVKLTA---AGEYGYYCEPHQGAGMVGKIIV
>plas_anava
--VKLGSDKGLLVFEPAKLTIKPGDTVEFLNNKVPPHNVVFDAALNPAKSADLAKSLSHKQLLMSPGQSTSTTFPADAPAGEYTFYCEPHRGAGMVGKITV
>plas_proho
VQIKMGTDKYAPLYEPKALSISAGDTVEFVMNKVGPHNVIFDK--VPAG-ES-APALSNTKLRIAPGSFYSVTLGT---PGTYSFYCTPHRGAGMVGTITV
>azup_achcy
VHMLNKGKDGAMVFEPASLKVAPGDTVTFIPTDK-GHNVETIKGMIPDG-AE-A-------FKSKINENYKVTFTA---PGVYGVKCTPHYGMGMVGVVEV

